// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: dya/input_module/input_module.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "dya.input_module";

export interface ModuleCapabilities {
  flags: number;
  kscan: boolean;
  encoder: boolean;
  adc: boolean;
  spi: boolean;
  i2c: boolean;
}

export interface ModuleProfile {
  id: number;
  name: string;
  capabilities: ModuleCapabilities | undefined;
  selected: boolean;
  applied: boolean;
  available: boolean;
}

export interface ModuleState {
  selectedProfileId: number;
  selectedProfileName: string;
  appliedProfileId: number;
  appliedProfileName: string;
  applied: boolean;
  rebootRequired: boolean;
  profiles: ModuleProfile[];
  source: number;
  status: number;
}

export interface GetStateRequest {
}

export interface GetStateResponse {
  state: ModuleState | undefined;
}

export interface GetAllStatesRequest {
}

export interface GetAllStatesResponse {
  requestSent: boolean;
}

export interface SetSelectedRequest {
  profileId: number;
  target: number;
}

export interface SetSelectedResponse {
  state: ModuleState | undefined;
  requestSent: boolean;
  target: number;
}

export interface ErrorResponse {
  message: string;
}

export interface Request {
  getState?: GetStateRequest | undefined;
  setSelected?: SetSelectedRequest | undefined;
  getAllStates?: GetAllStatesRequest | undefined;
}

export interface Response {
  error?: ErrorResponse | undefined;
  getState?: GetStateResponse | undefined;
  setSelected?: SetSelectedResponse | undefined;
  getAllStates?: GetAllStatesResponse | undefined;
}

export interface StateNotification {
  state: ModuleState | undefined;
}

export interface Notification {
  state?: StateNotification | undefined;
}

function createBaseModuleCapabilities(): ModuleCapabilities {
  return { flags: 0, kscan: false, encoder: false, adc: false, spi: false, i2c: false };
}

export const ModuleCapabilities: MessageFns<ModuleCapabilities> = {
  encode(message: ModuleCapabilities, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.flags !== 0) {
      writer.uint32(8).uint32(message.flags);
    }
    if (message.kscan !== false) {
      writer.uint32(16).bool(message.kscan);
    }
    if (message.encoder !== false) {
      writer.uint32(24).bool(message.encoder);
    }
    if (message.adc !== false) {
      writer.uint32(32).bool(message.adc);
    }
    if (message.spi !== false) {
      writer.uint32(40).bool(message.spi);
    }
    if (message.i2c !== false) {
      writer.uint32(48).bool(message.i2c);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModuleCapabilities {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModuleCapabilities();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.flags = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.kscan = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.encoder = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.adc = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.spi = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.i2c = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ModuleCapabilities>): ModuleCapabilities {
    return ModuleCapabilities.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModuleCapabilities>): ModuleCapabilities {
    const message = createBaseModuleCapabilities();
    message.flags = object.flags ?? 0;
    message.kscan = object.kscan ?? false;
    message.encoder = object.encoder ?? false;
    message.adc = object.adc ?? false;
    message.spi = object.spi ?? false;
    message.i2c = object.i2c ?? false;
    return message;
  },
};

function createBaseModuleProfile(): ModuleProfile {
  return { id: 0, name: "", capabilities: undefined, selected: false, applied: false, available: false };
}

export const ModuleProfile: MessageFns<ModuleProfile> = {
  encode(message: ModuleProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.capabilities !== undefined) {
      ModuleCapabilities.encode(message.capabilities, writer.uint32(26).fork()).join();
    }
    if (message.selected !== false) {
      writer.uint32(32).bool(message.selected);
    }
    if (message.applied !== false) {
      writer.uint32(40).bool(message.applied);
    }
    if (message.available !== false) {
      writer.uint32(48).bool(message.available);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModuleProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModuleProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.capabilities = ModuleCapabilities.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.selected = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.applied = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.available = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ModuleProfile>): ModuleProfile {
    return ModuleProfile.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModuleProfile>): ModuleProfile {
    const message = createBaseModuleProfile();
    message.id = object.id ?? 0;
    message.name = object.name ?? "";
    message.capabilities = (object.capabilities !== undefined && object.capabilities !== null)
      ? ModuleCapabilities.fromPartial(object.capabilities)
      : undefined;
    message.selected = object.selected ?? false;
    message.applied = object.applied ?? false;
    message.available = object.available ?? false;
    return message;
  },
};

function createBaseModuleState(): ModuleState {
  return {
    selectedProfileId: 0,
    selectedProfileName: "",
    appliedProfileId: 0,
    appliedProfileName: "",
    applied: false,
    rebootRequired: false,
    profiles: [],
    source: 0,
    status: 0,
  };
}

export const ModuleState: MessageFns<ModuleState> = {
  encode(message: ModuleState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.selectedProfileId !== 0) {
      writer.uint32(8).uint32(message.selectedProfileId);
    }
    if (message.selectedProfileName !== "") {
      writer.uint32(18).string(message.selectedProfileName);
    }
    if (message.appliedProfileId !== 0) {
      writer.uint32(24).uint32(message.appliedProfileId);
    }
    if (message.appliedProfileName !== "") {
      writer.uint32(34).string(message.appliedProfileName);
    }
    if (message.applied !== false) {
      writer.uint32(40).bool(message.applied);
    }
    if (message.rebootRequired !== false) {
      writer.uint32(48).bool(message.rebootRequired);
    }
    for (const v of message.profiles) {
      ModuleProfile.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.source !== 0) {
      writer.uint32(64).uint32(message.source);
    }
    if (message.status !== 0) {
      writer.uint32(72).int32(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModuleState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModuleState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.selectedProfileId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.selectedProfileName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.appliedProfileId = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.appliedProfileName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.applied = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.rebootRequired = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.profiles.push(ModuleProfile.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.source = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.status = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ModuleState>): ModuleState {
    return ModuleState.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModuleState>): ModuleState {
    const message = createBaseModuleState();
    message.selectedProfileId = object.selectedProfileId ?? 0;
    message.selectedProfileName = object.selectedProfileName ?? "";
    message.appliedProfileId = object.appliedProfileId ?? 0;
    message.appliedProfileName = object.appliedProfileName ?? "";
    message.applied = object.applied ?? false;
    message.rebootRequired = object.rebootRequired ?? false;
    message.profiles = object.profiles?.map((e) => ModuleProfile.fromPartial(e)) || [];
    message.source = object.source ?? 0;
    message.status = object.status ?? 0;
    return message;
  },
};

function createBaseGetStateRequest(): GetStateRequest {
  return {};
}

export const GetStateRequest: MessageFns<GetStateRequest> = {
  encode(_: GetStateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStateRequest>): GetStateRequest {
    return GetStateRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetStateRequest>): GetStateRequest {
    const message = createBaseGetStateRequest();
    return message;
  },
};

function createBaseGetStateResponse(): GetStateResponse {
  return { state: undefined };
}

export const GetStateResponse: MessageFns<GetStateResponse> = {
  encode(message: GetStateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      ModuleState.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = ModuleState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetStateResponse>): GetStateResponse {
    return GetStateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetStateResponse>): GetStateResponse {
    const message = createBaseGetStateResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? ModuleState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseGetAllStatesRequest(): GetAllStatesRequest {
  return {};
}

export const GetAllStatesRequest: MessageFns<GetAllStatesRequest> = {
  encode(_: GetAllStatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllStatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllStatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetAllStatesRequest>): GetAllStatesRequest {
    return GetAllStatesRequest.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<GetAllStatesRequest>): GetAllStatesRequest {
    const message = createBaseGetAllStatesRequest();
    return message;
  },
};

function createBaseGetAllStatesResponse(): GetAllStatesResponse {
  return { requestSent: false };
}

export const GetAllStatesResponse: MessageFns<GetAllStatesResponse> = {
  encode(message: GetAllStatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.requestSent !== false) {
      writer.uint32(8).bool(message.requestSent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetAllStatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetAllStatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.requestSent = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<GetAllStatesResponse>): GetAllStatesResponse {
    return GetAllStatesResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GetAllStatesResponse>): GetAllStatesResponse {
    const message = createBaseGetAllStatesResponse();
    message.requestSent = object.requestSent ?? false;
    return message;
  },
};

function createBaseSetSelectedRequest(): SetSelectedRequest {
  return { profileId: 0, target: 0 };
}

export const SetSelectedRequest: MessageFns<SetSelectedRequest> = {
  encode(message: SetSelectedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.profileId !== 0) {
      writer.uint32(8).uint32(message.profileId);
    }
    if (message.target !== 0) {
      writer.uint32(16).uint32(message.target);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSelectedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSelectedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.profileId = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.target = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSelectedRequest>): SetSelectedRequest {
    return SetSelectedRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSelectedRequest>): SetSelectedRequest {
    const message = createBaseSetSelectedRequest();
    message.profileId = object.profileId ?? 0;
    message.target = object.target ?? 0;
    return message;
  },
};

function createBaseSetSelectedResponse(): SetSelectedResponse {
  return { state: undefined, requestSent: false, target: 0 };
}

export const SetSelectedResponse: MessageFns<SetSelectedResponse> = {
  encode(message: SetSelectedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      ModuleState.encode(message.state, writer.uint32(10).fork()).join();
    }
    if (message.requestSent !== false) {
      writer.uint32(16).bool(message.requestSent);
    }
    if (message.target !== 0) {
      writer.uint32(24).uint32(message.target);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SetSelectedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSetSelectedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = ModuleState.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.requestSent = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.target = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<SetSelectedResponse>): SetSelectedResponse {
    return SetSelectedResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SetSelectedResponse>): SetSelectedResponse {
    const message = createBaseSetSelectedResponse();
    message.state = (object.state !== undefined && object.state !== null)
      ? ModuleState.fromPartial(object.state)
      : undefined;
    message.requestSent = object.requestSent ?? false;
    message.target = object.target ?? 0;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "" };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseRequest(): Request {
  return { getState: undefined, setSelected: undefined, getAllStates: undefined };
}

export const Request: MessageFns<Request> = {
  encode(message: Request, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.getState !== undefined) {
      GetStateRequest.encode(message.getState, writer.uint32(10).fork()).join();
    }
    if (message.setSelected !== undefined) {
      SetSelectedRequest.encode(message.setSelected, writer.uint32(18).fork()).join();
    }
    if (message.getAllStates !== undefined) {
      GetAllStatesRequest.encode(message.getAllStates, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Request {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.getState = GetStateRequest.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.setSelected = SetSelectedRequest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.getAllStates = GetAllStatesRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Request>): Request {
    return Request.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Request>): Request {
    const message = createBaseRequest();
    message.getState = (object.getState !== undefined && object.getState !== null)
      ? GetStateRequest.fromPartial(object.getState)
      : undefined;
    message.setSelected = (object.setSelected !== undefined && object.setSelected !== null)
      ? SetSelectedRequest.fromPartial(object.setSelected)
      : undefined;
    message.getAllStates = (object.getAllStates !== undefined && object.getAllStates !== null)
      ? GetAllStatesRequest.fromPartial(object.getAllStates)
      : undefined;
    return message;
  },
};

function createBaseResponse(): Response {
  return { error: undefined, getState: undefined, setSelected: undefined, getAllStates: undefined };
}

export const Response: MessageFns<Response> = {
  encode(message: Response, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.error !== undefined) {
      ErrorResponse.encode(message.error, writer.uint32(10).fork()).join();
    }
    if (message.getState !== undefined) {
      GetStateResponse.encode(message.getState, writer.uint32(18).fork()).join();
    }
    if (message.setSelected !== undefined) {
      SetSelectedResponse.encode(message.setSelected, writer.uint32(26).fork()).join();
    }
    if (message.getAllStates !== undefined) {
      GetAllStatesResponse.encode(message.getAllStates, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Response {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.error = ErrorResponse.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.getState = GetStateResponse.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.setSelected = SetSelectedResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.getAllStates = GetAllStatesResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Response>): Response {
    return Response.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Response>): Response {
    const message = createBaseResponse();
    message.error = (object.error !== undefined && object.error !== null)
      ? ErrorResponse.fromPartial(object.error)
      : undefined;
    message.getState = (object.getState !== undefined && object.getState !== null)
      ? GetStateResponse.fromPartial(object.getState)
      : undefined;
    message.setSelected = (object.setSelected !== undefined && object.setSelected !== null)
      ? SetSelectedResponse.fromPartial(object.setSelected)
      : undefined;
    message.getAllStates = (object.getAllStates !== undefined && object.getAllStates !== null)
      ? GetAllStatesResponse.fromPartial(object.getAllStates)
      : undefined;
    return message;
  },
};

function createBaseStateNotification(): StateNotification {
  return { state: undefined };
}

export const StateNotification: MessageFns<StateNotification> = {
  encode(message: StateNotification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      ModuleState.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StateNotification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStateNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = ModuleState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<StateNotification>): StateNotification {
    return StateNotification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StateNotification>): StateNotification {
    const message = createBaseStateNotification();
    message.state = (object.state !== undefined && object.state !== null)
      ? ModuleState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseNotification(): Notification {
  return { state: undefined };
}

export const Notification: MessageFns<Notification> = {
  encode(message: Notification, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.state !== undefined) {
      StateNotification.encode(message.state, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Notification {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotification();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.state = StateNotification.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<Notification>): Notification {
    return Notification.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Notification>): Notification {
    const message = createBaseNotification();
    message.state = (object.state !== undefined && object.state !== null)
      ? StateNotification.fromPartial(object.state)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
