#pragma once

#define ZMK_INPUT_MODULE_CAP_KSCAN 0x01
#define ZMK_INPUT_MODULE_CAP_ENCODER 0x02
#define ZMK_INPUT_MODULE_CAP_ADC 0x04
#define ZMK_INPUT_MODULE_CAP_SPI 0x08
#define ZMK_INPUT_MODULE_CAP_I2C 0x10
